language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
dist: xenial

install:
  - if [[ -n $TRAVIS_TAG ]]; then unset BUILD_TAG TWINE_REPOSITORY_URL; fi
  # Use [-> test!!] the wheel as installation medium:
  - python setup.py egg_info -b "$BUILD_TAG" sdist bdist_wheel
  - pip install dist/*.whl

  - pip install coverage coveralls
  - pip install twine flake8 docutils pygments

script:
  - twine check dist/*
  - flake8

  # Safeguard against importing from local folder:
  - mv minrpc _minrpc
  - coverage run --source=minrpc -p test/test_rpc.py -v
  - mv _minrpc minrpc

after_success:
  - coverage combine
  - coveralls

jobs:
  include:
    - stage: deploy
      name: Upload release to PyPI
      python: "3.6"
      if: tag is present OR branch = test-release
      script: twine upload dist/*
      after_success: true
      env:
        - BUILD_TAG=dev$TRAVIS_BUILD_NUMBER
        - TWINE_REPOSITORY_URL=https://test.pypi.org/legacy/
        - TWINE_USERNAME=hibtc-deploy
        # TWINE_PASSWORD
        - secure: "bGVhGeCTN56kZi5gYiqOAiKbj6kaDTMg5oeM1ENjvxp5X1TIVurIP1ucWyu88THLFno0zW69EadntXCKhM22kvCHYly+k8d1VOzKCE8nt4FemGIt+HGVSwollKuatIhwUop5QhtxEu3MmxOScxZWfelatOE/z8r3gRZyi0VBNwlEcyhavBfyJyhNBDcCAEj7i/BLnse37em/rrrHI0h6ZFAxuufEWyZ7DWienv6ZxRF2XJUfTZ0yMueBCtBHn9io73ueAeCWm6EWFYv3tiZldjhsNS7+r/eSWkuxHAl/YqwRLlsLOEFCxRGGwAC0s2TNLS4+XGblRLSUtB87227/gMbJR08Ris6mtY151egpKNFqgy//asHmbedBHDPSZfQyDmc+Ygq+fjsVpHaHXA5A1PZiUtqxrSJOGprCUP4yd39j06ccf4fCEjUO3BjRBFz7UV4lLZSQTUGLNdQ+LQccljsujRfRDzxCZTbKVpGaPcEd1dNaFK6tS09QwtnUn5HmNcLoDDQk1kP69sJhM3nWRP3zaL7E8UvmL41mpf+ZMuT//4mytf4f6dmmVfoFj98pSFac8Lz7B0ErkKdWpMo9pAXUOEBdKtQpPqc8yl6KOYfXnfuIqKmrNmyO/u7ZWjDdz+vf2SPzZBI0ulVdN7g3QHzwMBYK2/oJPRMl3e63mFk="
