language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

dist: trusty
sudo: false

install:
  # Use [-> test!!] the source distribution as installation medium:
  - python setup.py sdist
  - pip install ./dist/*.tar.gz

  - pip install coverage coveralls
  - pip install flake8 docutils pygments

script:
  - python setup.py check -rs
  - flake8

  # Safeguard against importing from local folder:
  - mv minrpc _minrpc
  - coverage run --source=minrpc -p test/test_rpc.py -v
  - mv _minrpc minrpc

after_success:
  - coverage combine
  - coveralls

jobs:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true
