language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

dist: trusty
sudo: false

install:
  # Use [-> test!!] the source distribution as installation medium:
  - python setup.py sdist
  - pip install ./dist/*.tar.gz

  # Safeguard against importing from local folder:
  - rm -r minrpc

  - pip install nose coverage coveralls

script:
  - coverage run --source=minrpc -p test/test_rpc.py -v

after_success:
  - git checkout minrpc         # restore deleted folder
  - coverage combine
  - coveralls

jobs:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true
